services:
  - type: web
    name: university-backend
    env: docker
    rootDir: backend
    dockerfilePath: ./backend/Dockerfile
    plan: standard
    healthCheckPath: /actuator/health
    numInstances: 1
    envVars:
      - key: PORT
        value: 8080
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_DATASOURCE_URL
        sync: false   # Configure in Render dashboard
      - key: SPRING_DATASOURCE_USERNAME
        sync: false   # Configure in Render dashboard
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false   # Configure in Render dashboard
      - key: SERVER_PORT
        value: 8080
    disk:
      name: tmp
      mountPath: /tmp
      sizeGB: 1

  - type: web
    name: university-frontend
    env: docker
    rootDir: frontend
    dockerfilePath: ./frontend/Dockerfile
    plan: starter
    buildCommand: npm ci && npm run build
    startCommand: nginx -g 'daemon off;'
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_URL
        fromService:
          name: university-backend
          type: web
          property: url
        value: https://university-backend.onrender.com/api  # This will be overridden by fromService
      - key: REACT_APP_AUTH_URL
        fromService:
          name: university-backend
          type: web
          property: url
        value: https://university-backend.onrender.com/auth  # This will be overridden by fromService
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache