name: Deploy to Railway

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Railway CLI
        run: npm i -g @railway/cli

      - name: Deploy backend
        working-directory: backend
        env:
          RAILWAY_TOKEN: "ecd29627-07bd-419e-a505-3340e18a0ada"
        run: |
          railway up --service "backend" --yes

      - name: Deploy frontend
        working-directory: frontend
        env:
          RAILWAY_TOKEN: "ecd29627-07bd-419e-a505-3340e18a0ada"
        run: |
          railway up --service "frontend" --yes
